# Generated by Django 5.0.6 on 2024-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=140)),
                ('data', models.CharField(max_length=50)),
                ('imagem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('imagem', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
